# Generated by Django 5.2.4 on 2025-07-31 13:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('coupon_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe'), ('free_shipping', 'Livraison gratuite')], max_length=20, verbose_name='Type de coupon')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valeur')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Montant minimum de commande')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Utilisations maximum')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('valid_from', models.DateTimeField(verbose_name='Valide à partir de')),
                ('valid_until', models.DateTimeField(verbose_name="Valide jusqu'au")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('shipping', 'Livraison'), ('billing', 'Facturation')], default='shipping', max_length=20, verbose_name="Type d'adresse")),
                ('is_default', models.BooleanField(default=False, verbose_name='Adresse par défaut')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Société')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='Adresse')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse")),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='État/Région')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Clé de session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de commande')),
                ('order_status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('processing', 'En préparation'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=20, verbose_name='Statut de commande')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('failed', 'Échouée'), ('refunded', 'Remboursée')], default='pending', max_length=20, verbose_name='Statut de paiement')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Frais de port')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Montant de la remise')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Méthode de paiement')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, verbose_name='ID Payment Intent Stripe')),
                ('shipping_method', models.CharField(default='standard', max_length=50, verbose_name='Méthode de livraison')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de suivi')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='Date de livraison estimée')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_orders', to='checkout.address', verbose_name='Adresse de facturation')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders', to='checkout.address', verbose_name='Adresse de livraison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total')),
                ('customizations', models.JSONField(blank=True, default=dict, verbose_name='Personnalisations')),
                ('flavor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.flavor', verbose_name='Parfum')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.order', verbose_name='Commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('customizations', models.JSONField(blank=True, default=dict, verbose_name='Personnalisations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.cart', verbose_name='Panier')),
                ('flavor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.flavor', verbose_name='Parfum')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article du panier',
                'verbose_name_plural': 'Articles du panier',
                'unique_together': {('cart', 'product', 'flavor')},
            },
        ),
    ]
